### ISSUE TITLE
Inventory full of skill fragments upon new spawn

### ISSUE THREAD

**Issue by D-Bigboy-302** [Floris0106/Rereskillable-Rereforked#3]
Forge Version: 1.16.5-36.2.19
Mod Version: 1.0.1

When the skill fragment leveling is set to true, upon creating a new world my inventory is full of skill fragments.

![2021-12-01_05 43 23](https://user-images.githubusercontent.com/61896885/144221003-a03fcc2d-5695-46eb-95a0-ae79378bbb1c.png)

Here's the log
[latest.log](https://github.com/Floris0106/Rereskillable-Rereforked/files/7633155/latest.log)
:

**Comment by Floris0106** [comment]
Hmm, that's not supposed to happen, can you give a list of mods in this instance? Also, do you have any advancements unlocked right after creating a new world?

**Comment by D-Bigboy-302** [comment]
Yeah I have mods that give you advancements upon joining new world. I did some more testing and it seems to be a mod compat.

I have like 200 mods. Idk how to list em all without taking an hour, so I'll do some more messing around to see what mod or mods specifically are causing a problem.

**Comment by Floris0106** [comment]
well, I don't know whether you still want to earn skill fragments through getting advancements, if you don't, you can just tweak the config to never give any skill fragments, and make some other way to get them. If you do, well this is technically intentional, so i can't really "fix" it. i could maybe make some workaround, but i think that wouldn't be a good idea.
